### ISSUE TITLE
Style data points on the map via MapBox API

### ISSUE THREAD

**Issue by theecrit** [openoakland/woeip#365] opened 2021-09-15 03:25 UTC
## Description
Style data points on the map according to rules in #237.

## Success criteria
- [ ] TBD

## Dependencies
- Requires completion of #366 first.

**Comment by exchrotek** [comment] 2021-09-29 02:04
@kwonangela7  to break down further in the next sprint. Some of the sub-tasks that result may require pair programming.

**Comment by kwonangela7** [comment] 2021-11-20 18:45
I'm closing this ticket as it's essentially a duplicate of #237

**Closed as completed by kwonangela7** 2021-11-20 18:45 UTC
Labels: issue type: enhancement, status: needs definition, milestone: MVP, component: front-end
