### ISSUE TITLE
As a user, I want to confirm session details after uploading my pair of files before saving them to the database. 

### ISSUE THREAD

**Issue by Ajay-Vishwanath** [openoakland/woeip#206] opened 2020-04-29 20:41 UTC
_Description_

I have submitted my log and CSV files from a single session, and I'd like to confirm the details concerning collection date, start time, and collection device before sending that information to the server.

_Acceptance Criteria_

- [ ] User can change ~each respective field~ device name per the design prototype
- ~[ ] User interface includes the calendar and time select components~
- [ ] All open questions in Issue have been answered or moved into new Issues.

_Dependencies and Assumptions_

- View will be built in React
- Semantic UI for the calendar component(?)
- 'Cancel Upload' modal will be handled in a separate issue

_Related Documentation_

- [Wireframes Parent File](https://www.figma.com/file/IZw8VvX1CsRc764CTvg4aRSU/WOAQ-Wireframes-Parent-File?node-id=340%3A5671l) - going off of the "Upload Flow v5: Happy Path Prototype"
- [WOAQ-Data-Flow-Diagram-v5.pdf](https://github.com/openoakland/woeip/files/4554489/WOAQ-Data-Flow-Diagram-v5.1.pdf)

**Comment by TangoYankee** [comment] 2020-04-29 21:13
Related #132 Correct Inaccurate MetaData

**Comment by TangoYankee** [comment] 2020-04-30 00:39
@theecrit I'm not sure whether this has been mentioned in the past- the `start` and `end times` are used as parameters of the `Collection` rather than the `Pollutant`. The pollutants will use the times listed in the files, regardless of what the user inputs. This is actually a good thing. The users will not have as accurate an idea of the start time as the files do and it's important that the time is correct to the second. 

If the user thinks the times are wrong, the files are either from the incorrect session or they are corrupted. Also, if the user changes the start time and is off by a day a month or even a year, then the `collection` and its `pollutants` will disagree with each other on when they were taken.

@Ajay-Vishwanath I'm not sure whether this quirk should prompt a design change in the associated components

**Comment by theecrit** [comment] 2020-04-30 17:02
@Ajay-Vishwanath This is duplicate of #132, not just related — since 132 is more detailed, I'm going to close this one and reassign 132 to you. 

@TangoYankee Two things:

> If the user thinks the times are wrong, the files are either from the incorrect session or they are corrupted.

Yep, this is a good catch. One possible solution is to make the field not editable, and include some help text to the effect of "Wrong date or time? You may have uploaded the wrong file. <ins>Try again</ins>." I'll run this by Niels and Kimberly in Slack.

> the start and end times are used as parameters of the `Collection` rather than the `Pollutant`

According to the latest version of the [database schema](https://user-images.githubusercontent.com/32755410/80737764-d5022000-8ac8-11ea-9bdf-005eb350f6e9.png), `Pollutant` is simply the name of the pollutant being measured. It should have no time/date-related values assigned to it.

If the actual database has been changed and the attached schema referenced above is no longer valid, we should update the schema ASAP. I'm happy to do that with some direction around what the current state actually is. And we need to understand why it was changed.

**Comment by TangoYankee** [comment] 2020-04-30 18:03
> According to the latest version of the database schema, Pollutant is simply the name of the pollutant being measured. It should have no time/date-related values assigned to it.

@theecrit you are correct. In my original comment, `Pollutant` should read `TimeGeo` referenced by `PollutantValue`. The database hasn't been changed but I believe the quirk still remains.

**Closed as completed** 2020-05-06 21:03 UTC
Labels: milestone: MVP, component: user interface, feature: upload data
